### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by Cloud-Resolved** [UoM-maul1609/bin-microphysics-model#1]
I got a Fortran runtime error, when I execute "./main.exe namelist.basic".
Here is the log:
```
At line 311 of file bin_microphysics_module.f90 (unit = 8, file = 'namelist.run')
Fortran runtime error: Cannot match namelist object name .false.

Error termination. Backtrace:
#0  0x7fd71b823960 in ???
#1  0x7fd71b8244d9 in ???
#2  0x7fd71b82510f in ???
#3  0x7fd71ba729b4 in ???
#4  0x7fd71ba7bd6d in ???
#5  0x7fd71ba7c0e3 in ???
#6  0x5561a6f9b625 in __bmm_MOD_read_in_bmm_namelist
        at /home/liurw/Documents/bin-microphysics-model/bin_microphysics_module.f90:311
#7  0x5561a6f703dd in MAIN__
        at /home/liurw/Documents/bin-microphysics-model/main.f90:57
#8  0x5561a6f703dd in main
        at /home/liurw/Documents/bin-microphysics-model/main.f90:25
```

**Comment by maul1609** [comment]
Thanks, I've just seen the issue and will resolve it. It is just an old namelist with different variables in it.

**Comment by maul1609** [comment]
Done
